name: Register
main: me.bibo38.Register.Register
version: 0.82
author: bibo38
softdepend: [Vault]
commands:
  register:
    description: Register you on the Server
    usage: /register [Password]
permissions:
  register.register:
    description: Allows a player to use the register command!
    default: false